use_frameworks!

platform :ios, '10.0'

target 'TestingLibCustomButton_Example' do
  pod 'TestingLibCustomButton', :path => '../'

  target 'TestingLibCustomButton_Tests' do
    inherit! :search_paths

    
  end
end
